version: "3.9"
services:
  db:
    image: postgres:16
    container_name: mededu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mededu
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build:
      context: ../services/api
      dockerfile: ../../infra/Dockerfile.api
    env_file:
      - ../services/api/.env
    depends_on:
      - db
    ports: ["4000:4000"]

  ml:
    build:
      context: ../services/ml
      dockerfile: ../../infra/Dockerfile.ml
    environment:
      - MODEL_ID=google/medgemma-4b-it
    ports: ["8000:8000"]

volumes:
  dbdata:
